"""Concolic test-input generation for small, pure Python functions.

The public entry point is :func:`explore_file`.  The implementation keeps the
concrete and symbolic executions together, so each newly solved path is
replayed as an ordinary set of Python values.
"""

from .artifacts import (
    BehaviorObservation,
    PytestGenerationResult,
    ReplayResult,
    ReplayStatus,
    behavior_equal,
    compare_observations,
    generate_pytest,
    minimize_runs,
    replay_runs,
)
from .core.runtime import (
    BranchCoverage,
    ConcolicError,
    ContractCounterexample,
    CoverageSnapshot,
    ExecutionOutcome,
    ExplorationResult,
    ExplorationStatistics,
    IdentityToken,
    OperationObservation,
    OutcomeKind,
    RunRecord,
    SourceLocation,
)
from .exploration import clear_registered_contracts, explore_file, register_contract
from .project import (
    FunctionScanResult,
    FunctionTarget,
    InputSynthesisResult,
    InputSynthesizer,
    OperationCatalog,
    OperationSupport,
    OperationUse,
    ParameterTarget,
    ProjectScanResult,
    ScanAttempt,
    ScanStatus,
    discover_targets,
    discover_operations,
    scan_project,
)

__all__ = [
    "BranchCoverage",
    "BehaviorObservation",
    "ConcolicError",
    "ContractCounterexample",
    "CoverageSnapshot",
    "ExecutionOutcome",
    "ExplorationResult",
    "ExplorationStatistics",
    "FunctionScanResult",
    "FunctionTarget",
    "InputSynthesisResult",
    "InputSynthesizer",
    "IdentityToken",
    "OutcomeKind",
    "OperationCatalog",
    "OperationObservation",
    "OperationSupport",
    "OperationUse",
    "ParameterTarget",
    "ProjectScanResult",
    "PytestGenerationResult",
    "ReplayResult",
    "ReplayStatus",
    "RunRecord",
    "ScanAttempt",
    "ScanStatus",
    "SourceLocation",
    "behavior_equal",
    "compare_observations",
    "clear_registered_contracts",
    "discover_targets",
    "discover_operations",
    "explore_file",
    "generate_pytest",
    "minimize_runs",
    "replay_runs",
    "register_contract",
    "scan_project",
]
