"""Stable identities, metadata, and semantic facts shared by PyFlow IRs."""

from .catalog import IRCatalog, ProcedureIR
from .analysis_facts import (
    CallTarget,
    Capabilities,
    ContextualKey,
    PublishedIPASummary,
)
from .build_semantics import build_program_semantics, build_semantics
from .facts import FactResult, FactStore, Precision
from .ids import (
    AllocationSiteId,
    BlockId,
    CallSiteId,
    CodeId,
    ContextId,
    ContextSignature,
    EdgeId,
    IRRevision,
    InlineInstanceId,
    NodeId,
    ScopeId,
    SourceAnchor,
    SymbolId,
    ValueId,
)
from .index import (
    ensure_code_indexed,
    ensure_codes_indexed,
    index_cfg,
    index_code,
    index_program,
    rebuild_program_ir,
)
from .semantics import CallSite, ControlEffects, IRSemantics, OperationSemantics
from .source import (
    SourceMap,
    SourceOrigin,
    SourceSpan,
    SyntheticOrigin,
    TransformationFrame,
    RebuildProvenanceSeed,
    format_source,
    source_filename,
)
from .query import AnalysisFacts, MissingAnalysisFact, StaleAnalysisFacts
from .remap import IRRemap
from .storage import (
    AttributeStorage,
    CellStorage,
    GlobalStorage,
    LocalStorage,
    StorageLocation,
    SubscriptStorage,
    SummaryStorage,
    UnknownStorage,
)
from .symbols import Symbol, SymbolKind, SymbolTable, Value, ValueTable
from .verifier import IRVerificationError, verify_catalog

__all__ = [
    "AllocationSiteId",
    "AnalysisFacts",
    "AttributeStorage",
    "BlockId",
    "CallSite",
    "CallSiteId",
    "CallTarget",
    "CellStorage",
    "CodeId",
    "ContextId",
    "ContextSignature",
    "ContextualKey",
    "ControlEffects",
    "Capabilities",
    "FactResult",
    "FactStore",
    "EdgeId",
    "GlobalStorage",
    "IRCatalog",
    "IRRevision",
    "IRRemap",
    "IRSemantics",
    "IRVerificationError",
    "InlineInstanceId",
    "LocalStorage",
    "MissingAnalysisFact",
    "StaleAnalysisFacts",
    "NodeId",
    "OperationSemantics",
    "Precision",
    "PublishedIPASummary",
    "ProcedureIR",
    "RebuildProvenanceSeed",
    "ScopeId",
    "SourceAnchor",
    "SourceMap",
    "SourceOrigin",
    "SourceSpan",
    "StorageLocation",
    "SubscriptStorage",
    "SummaryStorage",
    "Symbol",
    "SymbolId",
    "SymbolKind",
    "SymbolTable",
    "TransformationFrame",
    "format_source",
    "source_filename",
    "SyntheticOrigin",
    "UnknownStorage",
    "Value",
    "ValueId",
    "ValueTable",
    "verify_catalog",
    "index_code",
    "index_program",
    "rebuild_program_ir",
    "ensure_code_indexed",
    "ensure_codes_indexed",
    "index_cfg",
    "build_semantics",
    "build_program_semantics",
]
