"""Generate replay-validated pytest tests from concolic executions."""

from __future__ import annotations

import math
from dataclasses import dataclass
from pathlib import Path
from typing import Any

from .corpus import minimize_runs
from .replay import ReplayResult, ReplayStatus, replay_runs
from ..core.runtime import ExplorationResult, OutcomeKind, RunRecord


@dataclass(frozen=True)
class PytestGenerationResult:
    source: str
    selected_runs: tuple[RunRecord, ...]
    emitted_runs: tuple[RunRecord, ...]
    replays: tuple[ReplayResult, ...]
    skipped: tuple[str, ...]

    def to_dict(self) -> dict[str, Any]:
        return {
            "selected_runs": len(self.selected_runs),
            "emitted_tests": len(self.emitted_runs),
            "skipped": list(self.skipped),
            "replays": [replay.to_dict() for replay in self.replays],
        }


def generate_pytest(
    path: str | Path,
    result: ExplorationResult,
) -> PytestGenerationResult:
    """Select, replay, and render deterministic tests for an exploration."""
    source_path = Path(path).resolve()
    selected = minimize_runs(result.runs, result.counterexamples)
    replays = replay_runs(source_path, result.entry, selected)
    emitted: list[RunRecord] = []
    skipped: list[str] = []
    tests: list[str] = []

    for index, replay in enumerate(replays, 1):
        run = replay.run
        if replay.status is not ReplayStatus.MATCHED:
            skipped.append(
                f"{list(run.inputs)!r}: replay {replay.status.value}: "
                + "; ".join(replay.differences)
            )
            continue
        try:
            test_lines = _render_test(result.entry, run, index)
        except ValueError as error:
            skipped.append(f"{list(run.inputs)!r}: {error}")
            continue
        emitted.append(run)
        tests.extend(test_lines)

    source = _render_header(source_path, result.entry) + "\n".join(tests)
    return PytestGenerationResult(
        source=source,
        selected_runs=selected,
        emitted_runs=tuple(emitted),
        replays=replays,
        skipped=tuple(skipped),
    )


def _render_header(path: Path, entry: str) -> str:
    return f"""# Generated by PyFlow concolic exploration.
import asyncio
import copy
import importlib.util
import inspect
import sys
from pathlib import Path


_TARGET = Path({_literal_source(str(path))})
_ENTRY = {_literal_source(entry)}


def _load_entry():
    module_name = "_pyflow_generated_target"
    specification = importlib.util.spec_from_file_location(module_name, _TARGET)
    assert specification is not None and specification.loader is not None
    module = importlib.util.module_from_spec(specification)
    parent = str(_TARGET.parent)
    sys.path.insert(0, parent)
    sys.modules[module_name] = module
    try:
        specification.loader.exec_module(module)
        return getattr(module, _ENTRY)
    finally:
        sys.modules.pop(module_name, None)
        if sys.path and sys.path[0] == parent:
            sys.path.pop(0)


def _invoke(arguments):
    result = _load_entry()(*arguments)
    if inspect.isawaitable(result):
        return asyncio.run(_await_value(result))
    return result


async def _await_value(awaitable):
    return await awaitable


"""


def _render_test(entry: str, run: RunRecord, index: int) -> list[str]:
    inputs = _literal_source(run.inputs)
    post_inputs = _literal_source(run.post_inputs or run.inputs)
    name = f"test_{_identifier(entry)}_{index:03d}"
    lines = [f"def {name}():", f"    arguments = copy.deepcopy({inputs})"]
    if run.outcome.kind is OutcomeKind.RETURNED:
        expected = _literal_source(run.result)
        lines.append("    result = _invoke(arguments)")
        lines.append(f"    assert result == {expected}")
    elif run.outcome.kind is OutcomeKind.TARGET_EXCEPTION:
        exception_type = _literal_source(run.outcome.exception_type or "Exception")
        message = _literal_source(run.outcome.message or "")
        lines.extend(
            [
                "    try:",
                "        _invoke(arguments)",
                "    except Exception as error:",
                f"        assert type(error).__name__ == {exception_type}",
                f"        assert str(error) == {message}",
                "    else:",
                "        raise AssertionError('expected target exception')",
            ]
        )
    else:
        raise ValueError(f"cannot emit outcome {run.outcome.kind.value}")
    lines.append(f"    assert arguments == {post_inputs}")
    lines.extend(["", ""])
    return lines


def _literal_source(value: Any) -> str:
    if value is None or isinstance(value, (bool, int, str, bytes)):
        return repr(value)
    if isinstance(value, float):
        if not math.isfinite(value):
            raise ValueError(f"cannot emit non-finite float {value!r}")
        return repr(value)
    if isinstance(value, list):
        return "[" + ", ".join(_literal_source(item) for item in value) + "]"
    if isinstance(value, tuple):
        items = ", ".join(_literal_source(item) for item in value)
        comma = "," if len(value) == 1 else ""
        return f"({items}{comma})"
    if isinstance(value, dict):
        return (
            "{"
            + ", ".join(
                f"{_literal_source(key)}: {_literal_source(item)}" for key, item in value.items()
            )
            + "}"
        )
    if isinstance(value, set):
        if not value:
            return "set()"
        rendered_items = sorted((_literal_source(item) for item in value))
        return "{" + ", ".join(rendered_items) + "}"
    raise ValueError(f"cannot emit value of type {type(value).__name__}")


def _identifier(name: str) -> str:
    identifier = "".join(character if character.isalnum() else "_" for character in name)
    return identifier or "entry"
