"""IFDS/IDE interprocedural dataflow engine."""

from .cfg_adapter import (
    annotation_invokes_cfg_resolver,
    CFGNode,
    CFGSupergraphAdapter,
    assigned_locals,
    build_supergraph_from_cfgs,
    composite_cfg_resolver,
    direct_call_cfg_resolver,
    extract_call_expression,
    iter_call_expressions,
    iter_call_expressions_in_eval_order,
    named_call_cfg_resolver,
)
from .problem import (
    ComposedEdgeFunction,
    ConstantEdgeFunction,
    EdgeFunction,
    FactTransition,
    IDEProblem,
    IdentityEdgeFunction,
    IFDSProblem,
    JoinedEdgeFunction,
    ValueTransition,
)
from .solver import IDEResult, IDESolver, IFDSResult, IFDSSolver, PathEdge
from .solver import PropagationTrace, SolverStatistics
from .supergraph import Supergraph, SupergraphError
from .clients.nullness import (
    ExpressionNullFact,
    InterproceduralNullnessAnalysis,
    NullnessAnalysisResult,
    NullnessFinding,
    SlotNullFact,
    analyze_nullness,
)
from .clients.taint import (
    ExpressionTaintFact,
    InterproceduralTaintAnalysis,
    SlotTaintFact,
    TaintAnalysisResult,
    TaintConfiguration,
    TaintFinding,
    analyze_taint,
)
from .clients.typestate import (
    ExpressionResourceFact,
    InterproceduralTypestateAnalysis,
    ResourceStateFact,
    TypestateAnalysisResult,
    TypestateConfiguration,
    TypestateFinding,
    analyze_typestate,
)
from .transfers import (
    actual_argument_expressions,
    actual_parameters,
    bind_call_arguments,
    collect_locals,
    formal_parameters,
    identity_unless_killed,
    resolve_call_name,
)

__all__ = [
    "ComposedEdgeFunction",
    "ConstantEdgeFunction",
    "CFGNode",
    "CFGSupergraphAdapter",
    "EdgeFunction",
    "ExpressionNullFact",
    "ExpressionResourceFact",
    "ExpressionTaintFact",
    "FactTransition",
    "IDEProblem",
    "IDEResult",
    "IDESolver",
    "IdentityEdgeFunction",
    "IFDSProblem",
    "IFDSResult",
    "IFDSSolver",
    "InterproceduralNullnessAnalysis",
    "JoinedEdgeFunction",
    "InterproceduralTypestateAnalysis",
    "PathEdge",
    "PropagationTrace",
    "NullnessAnalysisResult",
    "NullnessFinding",
    "SolverStatistics",
    "SlotNullFact",
    "Supergraph",
    "SupergraphError",
    "TaintAnalysisResult",
    "TaintConfiguration",
    "TaintFinding",
    "InterproceduralTaintAnalysis",
    "TypestateAnalysisResult",
    "TypestateConfiguration",
    "TypestateFinding",
    "ResourceStateFact",
    "SlotTaintFact",
    "actual_argument_expressions",
    "ValueTransition",
    "actual_parameters",
    "annotation_invokes_cfg_resolver",
    "analyze_nullness",
    "analyze_taint",
    "analyze_typestate",
    "assigned_locals",
    "bind_call_arguments",
    "build_supergraph_from_cfgs",
    "collect_locals",
    "composite_cfg_resolver",
    "direct_call_cfg_resolver",
    "extract_call_expression",
    "formal_parameters",
    "identity_unless_killed",
    "iter_call_expressions",
    "iter_call_expressions_in_eval_order",
    "named_call_cfg_resolver",
    "resolve_call_name",
]
