"""IFDS/IDE interprocedural dataflow engine."""

from .frontend.cfg_adapter import (
    CallEffect,
    CFGNode,
    CFGSupergraphAdapter,
    assigned_locals,
    build_supergraph_from_cfgs,
    composite_cfg_resolver,
    direct_call_cfg_resolver,
    extract_call_expression,
    iter_call_expressions,
    iter_call_expressions_in_eval_order,
    iter_suspension_expressions,
    fact_call_targets_cfg_resolver,
    ProcedureSemantics,
    SuspensionEffect,
)
from ..alias.flow_sensitive.model import (
    AllocationSensitivity,
    ContainerSensitivity,
    FieldSensitivity,
    HeapEscapeState,
    HeapLocation,
    HeapObject,
    HeapObjectFreshness,
    HeapObjectKind,
    HeapPolicy,
    HeapSelector,
    HeapWrite,
    UpdatePolicy,
)
from ..alias.flow_sensitive.domain.abstraction import (
    HeapAbstraction,
)
from ..alias.flow_sensitive.semantics.effects import (
    CALL_RETURN_COPY,
    CALL_RETURN_FRESH,
    CALL_RETURN_OPAQUE,
    CALL_RETURN_SUMMARY,
    HeapEffect,
    HeapEffectBuilder,
)
from ..alias.flow_sensitive.domain.summary import (
    HeapSummary,
    HeapSummaryBuilder,
)
from .core.problem import (
    ComposedEdgeFunction,
    ConstantEdgeFunction,
    EdgeFunction,
    FactTransition,
    GenFlow,
    IDEProblem,
    IdentityEdgeFunction,
    IdentityFlow,
    IFDSProblem,
    JoinedEdgeFunction,
    KillFlow,
    ValueTransition,
    ZERO,
    ZeroFact,
)
from .core.solver import (
    AnalysisStatus,
    CancellationToken,
    CallContext,
    IDEResult,
    IDESolver,
    IFDSResult,
    IFDSSolver,
    PathEdge,
    SolverLimitExceeded,
    SolverOptions,
)
from .core.solver import PropagationTrace, SolverStatistics
from .diagnostics import IFDSDiagnostic
from .queries import is_reached_prefix, verify_call_chain
from .reporting import AnalysisFinding, FlowStep, SourceSpan
from pyflow.util.cwe import cwe_ancestors, cwe_identifiers, normalize_cwe
from .core.supergraph import Supergraph, SupergraphError
from .core.backward import (
    BackwardIFDSProblem,
    BackwardIFDSSolver,
)
from .analyses.nullness import (
    ExpressionNullFact,
    InterproceduralNullnessAnalysis,
    NullFact,
    NullnessAnalysisResult,
    NullnessConfiguration,
    NullnessFinding,
    analyze_nullness,
)
from .modeling.registry import (
    Registry,
    load_registry,
)
from .analyses.typestate import (
    ExpressionResourceFact,
    InterproceduralTypestateAnalysis,
    ResourceStateFact,
    TypestateAnalysisResult,
    TypestateConfiguration,
    TypestateFinding,
    analyze_typestate,
)
from .modeling.typestate import (
    TypestateActionModel,
    TypestateEngine,
    TypestateExitObligation,
    TypestateProtocol,
    TypestateTransition,
    TypestateViolation,
    built_in_python_protocols,
    file_descriptor_protocol,
    lock_protocol,
    resource_lifecycle_protocol,
    socket_protocol,
    transaction_protocol,
)
from .core.transfers import (
    actual_argument_expressions,
    actual_parameters,
    bind_call_arguments,
    collect_locals,
    formal_parameters,
    identity_unless_killed,
)
from pyflow.language.python.ir_metadata import resolve_call_name

__all__ = [
    "BackwardIFDSProblem",
    "BackwardIFDSSolver",
    "AnalysisStatus",
    "AnalysisFinding",
    "CancellationToken",
    "CallContext",
    "CallEffect",
    "ComposedEdgeFunction",
    "ConstantEdgeFunction",
    "CFGNode",
    "CFGSupergraphAdapter",
    "CALL_RETURN_COPY",
    "CALL_RETURN_FRESH",
    "CALL_RETURN_OPAQUE",
    "CALL_RETURN_SUMMARY",
    "EdgeFunction",
    "ExpressionNullFact",
    "ExpressionResourceFact",
    "FactTransition",
    "FlowStep",
    "IFDSDiagnostic",
    "GenFlow",
    "IDEProblem",
    "IDEResult",
    "IDESolver",
    "IdentityEdgeFunction",
    "IdentityFlow",
    "IFDSProblem",
    "IFDSResult",
    "IFDSSolver",
    "InterproceduralNullnessAnalysis",
    "JoinedEdgeFunction",
    "InterproceduralTypestateAnalysis",
    "KillFlow",
    "load_registry",
    "PathEdge",
    "PropagationTrace",
    "ProcedureSemantics",
    "NullnessAnalysisResult",
    "NullnessConfiguration",
    "NullnessFinding",
    "Registry",
    "SolverStatistics",
    "SolverLimitExceeded",
    "SolverOptions",
    "NullFact",
    "Supergraph",
    "SuspensionEffect",
    "SupergraphError",
    "SourceSpan",
    "TypestateAnalysisResult",
    "TypestateActionModel",
    "TypestateConfiguration",
    "TypestateEngine",
    "TypestateExitObligation",
    "TypestateFinding",
    "TypestateProtocol",
    "TypestateTransition",
    "TypestateViolation",
    "ResourceStateFact",
    "ZERO",
    "ZeroFact",
    "actual_argument_expressions",
    "ValueTransition",
    "verify_call_chain",
    "actual_parameters",
    "analyze_nullness",
    "analyze_typestate",
    "assigned_locals",
    "bind_call_arguments",
    "built_in_python_protocols",
    "build_supergraph_from_cfgs",
    "collect_locals",
    "composite_cfg_resolver",
    "cwe_ancestors",
    "cwe_identifiers",
    "direct_call_cfg_resolver",
    "extract_call_expression",
    "formal_parameters",
    "AllocationSensitivity",
    "ContainerSensitivity",
    "FieldSensitivity",
    "HeapAbstraction",
    "HeapEffect",
    "HeapEffectBuilder",
    "HeapEscapeState",
    "HeapLocation",
    "HeapObject",
    "HeapObjectFreshness",
    "HeapObjectKind",
    "HeapPolicy",
    "HeapSelector",
    "HeapSummary",
    "HeapSummaryBuilder",
    "HeapWrite",
    "identity_unless_killed",
    "is_reached_prefix",
    "iter_call_expressions",
    "iter_call_expressions_in_eval_order",
    "iter_suspension_expressions",
    "normalize_cwe",
    "fact_call_targets_cfg_resolver",
    "resolve_call_name",
    "resource_lifecycle_protocol",
    "file_descriptor_protocol",
    "lock_protocol",
    "socket_protocol",
    "transaction_protocol",
    "UpdatePolicy",
]
