"""MIR-only tests for Python protocols generated by the runtime builder.

These avoid the Python frontend, so they independently check that call graph
edges emerge from ordinary fields, closures and the seven core instructions.
"""

from pyflow.analysis.callgraph.pycg_mir import analyze_program
from pyflow.ir.mir.builder import Builder, field
from pyflow.ir.mir.model import ListExpr, Literal, NewObject, Program, Var
from pyflow.ir.mir.runtime import Runtime


def runtime_program():
    """A minimal builtin object universe with no opaque analyzer semantics."""
    program = Program({}, "main")
    runtime = Runtime(program)
    main = Builder(program, "main")
    builtins = main.alloc(NewObject(), "builtins")
    main.assign("$builtins", builtins)
    classes = {}
    for name in Runtime.TYPES:
        cls = main.alloc(NewObject(), name)
        classes[name] = cls
        main.assign(field(builtins, name), cls)
        main.assign(field(cls, "$class"), main.alloc(Literal(True)))
    for name, cls in classes.items():
        main.assign(field(cls, "__class__"), classes["type"])
        bases = (cls,) if name == "object" else (cls, classes["object"])
        main.assign(field(cls, "__mro__"), main.alloc(ListExpr(bases)))
    for name, cls in (
        ("None", "NoneType"),
        ("NotImplemented", "NotImplementedType"),
        ("$missing", "object"),
        ("$state", "object"),
    ):
        main.assign(field(builtins, name), runtime.obj(main, cls))
    main.assign(runtime.exception, runtime.none)
    return program, runtime, main


def make_class(runtime, builder, name, methods, bases=()):
    cls = runtime.obj(builder, "type")
    builder.assign(field(cls, "$class"), runtime.raw(builder, True))
    builder.assign(field(cls, "__name__"), runtime.raw(builder, name))
    builder.assign(
        field(cls, "__mro__"),
        builder.alloc(ListExpr((cls, *bases, runtime.builtin("object")))),
    )
    for name, value in methods.items():
        builder.assign(field(cls, name), value)
    return cls


def source_function(program, runtime, name, emit_body):
    body = Builder(program, name)
    runtime.prologue(body)
    emit_body(body)
    body.finish()
    return name


def test_runtime_call_protocol_preserves_higher_order_arguments():
    program, runtime, main = runtime_program()
    leaf = source_function(program, runtime, "main.leaf", lambda b: b.ret(runtime.none))

    def apply_body(body):
        callback = body.bind(field(Var("$args"), 1))
        body.ret(runtime.call(body, callback))

    apply = source_function(program, runtime, "main.apply", apply_body)
    leaf_object = runtime.function(main, leaf)
    apply_object = runtime.function(main, apply)
    runtime.call(main, apply_object, (leaf_object,))
    main.finish()
    result = analyze_program(program, raise_on_truncation=True)
    assert result.call_graph.get()["main"] == {"main.apply"}
    # Path-insensitive analysis also traverses the helper's class-construction
    # branch. Its recursive environment can merge receiver-prefixed argument
    # lists, admitting extra targets. The callback must still be discovered.
    assert "main.leaf" in result.call_graph.get()["main.apply"]
    assert result.iterations < 100


def test_runtime_callable_instance_preserves_bound_receiver_and_callback():
    program, runtime, main = runtime_program()
    leaf = source_function(program, runtime, "main.leaf", lambda b: b.ret(runtime.none))

    def call_body(body):
        callback = body.bind(field(Var("$args"), 2))
        body.ret(runtime.call(body, callback))

    call = source_function(program, runtime, "main.Callable.__call__", call_body)
    cls = make_class(runtime, main, "Callable", {"__call__": runtime.function(main, call)})
    instance = runtime.obj(main, cls)
    runtime.call(main, instance, (runtime.function(main, leaf),))
    main.finish()
    result = analyze_program(program, raise_on_truncation=True)
    assert "main.Callable.__call__" in result.call_graph.get()["main"]
    assert "main.leaf" in result.call_graph.get()["main.Callable.__call__"]
    assert result.iterations < 100


def test_runtime_binary_protocol_discovers_forward_and_reflected_methods():
    program, runtime, main = runtime_program()
    add = source_function(program, runtime, "main.A.__add__", lambda b: b.ret(runtime.none))
    radd = source_function(program, runtime, "main.B.__radd__", lambda b: b.ret(runtime.none))
    left_class = make_class(runtime, main, "A", {"__add__": runtime.function(main, add)})
    right_class = make_class(runtime, main, "B", {"__radd__": runtime.function(main, radd)})
    runtime.invoke(
        main, "binary", (runtime.obj(main, left_class), runtime.obj(main, right_class)), "+"
    )
    main.finish()
    result = analyze_program(program, raise_on_truncation=True)
    assert result.call_graph.get()["main"] == {"main.A.__add__", "main.B.__radd__"}
    assert result.iterations < 100


def test_operator_implemented_by_callable_object_is_resolved_without_special_solver_rules():
    program, runtime, main = runtime_program()
    call = source_function(
        program, runtime, "main.Operator.__call__", lambda b: b.ret(runtime.none)
    )
    operator_class = make_class(
        runtime, main, "Operator", {"__call__": runtime.function(main, call)}
    )
    left_class = make_class(runtime, main, "A", {"__add__": runtime.obj(main, operator_class)})
    right_class = make_class(runtime, main, "B", {})
    runtime.invoke(
        main, "binary", (runtime.obj(main, left_class), runtime.obj(main, right_class)), "+"
    )
    main.finish()
    result = analyze_program(program, raise_on_truncation=True)
    assert result.call_graph.get()["main"] == {"main.Operator.__call__"}


def test_descriptor_returned_function_flows_into_the_following_call():
    program, runtime, main = runtime_program()
    leaf = source_function(program, runtime, "main.leaf", lambda b: b.ret(runtime.none))
    main.assign("leaf", runtime.function(main, leaf))
    getter = source_function(
        program,
        runtime,
        "main.Descriptor.__get__",
        lambda b: b.ret(field(Var("$parent"), "leaf")),
    )
    descriptor_class = make_class(
        runtime, main, "Descriptor", {"__get__": runtime.function(main, getter)}
    )
    instance_class = make_class(
        runtime, main, "A", {"attribute": runtime.obj(main, descriptor_class)}
    )
    attribute = runtime.invoke(
        main,
        "getattr",
        (runtime.obj(main, instance_class), runtime.raw(main, "attribute")),
    )
    runtime.call(main, attribute)
    main.finish()
    result = analyze_program(program, raise_on_truncation=True)
    assert {"main.Descriptor.__get__", "main.leaf"} <= result.call_graph.get()["main"]
    assert result.iterations < 100


def test_construction_calls_custom_new_and_init_through_synthetic_dispatch():
    program, runtime, main = runtime_program()

    def new_body(body):
        cls = body.bind(field(Var("$args"), 1))
        body.ret(runtime.obj(body, cls))

    new = source_function(program, runtime, "main.A.__new__", new_body)
    init = source_function(program, runtime, "main.A.__init__", lambda b: b.ret(runtime.none))
    cls = make_class(
        runtime,
        main,
        "A",
        {"__new__": runtime.function(main, new), "__init__": runtime.function(main, init)},
    )
    runtime.call(main, cls)
    main.finish()
    result = analyze_program(program, raise_on_truncation=True)
    assert {"main.A.__new__", "main.A.__init__"} <= result.call_graph.get()["main"]
    assert result.iterations < 100
